apiVersion: v1
kind: ResourceController
metadate:
  name: vpc-controller
spec:
  selector:
     VSwitchId: vsw-2ze73g8a3mlct8n7ow99r
  spec:
    Ecs.Create:
    - InstanceName: nova_vda
      Description: nova_vda_desc
      ImageId: suse11sp3_64_20G_aliaegis_20150428.vhd
      InstanceType: ecs.t1.xsmall
      SecurityGroupId:
      InternetChargeType: PayByBandwidth
      InternetMaxBandwidthIn: 200
      InternetMaxBandwidthOut: 100
      HostName: nova-bbc
      Password: Newmed!@s0bey
      IoOptimized: optimized
      SystemDisk.Category: cloud
      SystemDisk.Size: 20
      SystemDisk.DiskName: disk_a_1
      SystemDisk.Description: disk_a_1_desc
      PrivateIpAddress: 172.16.1.9
      InstanceChargeType: PrePaid
      Period: 12
      AutoRenew: True
      AutoRenewPeriod: 1
      KeyPairName: